--1.1
create table AUTHOR(
AUTHORID VARCHAR2(20) NOT NULL,
ANAME VARCHAR(20),
PRIMARY KEY(AUTHORID)
--1.2
CREATE TABLE PUBLISHER(
PUBLISHID VARCHAR(20) NOT NULL,
PUBNAME VARCHAR(20),
ADDRESS VARCHAR(30),
PRIMARY KEY(PUBLISHID)
)
--1.3
CREATE TABLE BRANCH(
LIBID VARCHAR(20) NOT NULL,
LNAME VARCHAR(20),
LLOCATION VARCHAR(30),
PRIMARY KEY(LIBID)
)
--1.4
CREATE TABLE CHIEF_EDITOR(
EDITOR_ID VARCHAR(20) NOT NULL,
ENAME VARCHAR(20),
PRIMARY KEY(EDITOR_ID)
)
--1.5
CREATE TABLE READER(
READERID VARCHAR2(20) NOT NULL,
RTYPE VARCHAR2(20),
RNAME VARCHAR2(20),
ADDRESS VARCHAR2(30),
PRIMARY KEY(READERID)
)




SELECT * FROM AUTHOR

DROP TABLE BOOK



--2.1
CREATE TABLE DOCUMENT(
DOCID VARCHAR2(20) NOT NULL,
TITLE VARCHAR2(20),
PDATE DATE,
PUBLISHERID VARCHAR(20),
PRIMARY KEY(DOCID),
FOREIGN KEY (PUBLISHERID) REFERENCES PUBLISHER
)
--2.2
CREATE TABLE BOOK(
DOCID VARCHAR(21) NOT NULL,
ISBN VARCHAR(2),
PRIMARY KEY(DOCID),
FOREIGN KEY (DOCID) REFERENCES DOCUMENT
)
--2.3
CREATE TABLE JOURNAL_VOLUME(
DOCID VARCHAR2(20) NOT NULL,
JVOLUME INTEGER,
EDITOR_ID VARCHAR2(20),
PRIMARY KEY(DOCID),
FOREIGN KEY (DOCID) REFERENCES DOCUMENT,
FOREIGN KEY (EDITOR_ID) REFERENCES CHIEF_EDITOR
)
--2.4
CREATE TABLE WRITES (
AUTHORID VARCHAR2(20) NOT NULL,
DOCID VARCHAR2(20) NOT NULL,
PRIMARY KEY(AUTHORID,DOCID),
FOREIGN KEY (AUTHORID) REFERENCES AUTHOR,
FOREIGN KEY (DOCID) REFERENCES BOOK
)
--2.5
CREATE TABLE JOURNAL_ISSUE(
DOCID VARCHAR2(20) NOT NULL,
ISSUE_NO VARCHAR2(20) NOT NULL,
SCOPE VARCHAR2(20) NOT NULL,
PRIMARY KEY(DOCID, ISSUE_NO),
FOREIGN KEY (DOCID) REFERENCES JOURNAL_VOLUME
)

--2.6
CREATE TABLE INV_EDITOR(
DOCID VARCHAR2(20) NOT NULL,
ISSUE_NO VARCHAR2(20) NOT NULL,
IENAME VARCHAR2(20) NOT NULL,
PRIMARY KEY(DOCID, ISSUE_NO, IENAME),
FOREIGN KEY (DOCID,ISSUE_NO) REFERENCES JOURNAL_ISSUE
)

--2.7
CREATE TABLE PROCEEDINGS(
DOCID VARCHAR2(20) NOT NULL,
CDATE DATE,
CLOCATION VARCHAR2(30),
CEDITOR VARCHAR2(20),
PRIMARY KEY(DOCID),
FOREIGN KEY (DOCID) REFERENCES DOCUMENT
)

--3.1
CREATE TABLE COPY(
DOCID VARCHAR2(20) NOT NULL,
COPYNO VARCHAR2(20) NOT NULL,
LIBID VARCHAR2(20) NOT NULL,
POSITION VARCHAR2(20),
PRIMARY KEY(DOCID, COPYNO, LIBID),
FOREIGN KEY (DOCID) REFERENCES DOCUMENT
)

--3.2
CREATE TABLE BORROWS(
BORNUMBER VARCHAR2(20) NOT NULL,
READERID VARCHAR2(20),
DOCID VARCHAR2(20),
COPYNO VARCHAR2(20),
LIBID VARCHAR2(20),
BDTIME DATE,
RDTIME DATE,
PRIMARY KEY(BORNUMBER),
FOREIGN KEY(DOCID, COPYNO, LIBID) REFERENCES COPY,
FOREIGN KEY(READERID) REFERENCES READER
)

CREATE TABLE RESERVES(
RESUMBER VARCHAR2(20) NOT NULL,
READERID VARCHAR2(20),
DOCID VARCHAR2(20),
COPYNO VARCHAR2(20),
LIBID VARCHAR2(20),
DTIME DATE,
PRIMARY KEY(RESUMBER),
FOREIGN KEY(DOCID, COPYNO, LIBID) REFERENCES COPY,
FOREIGN KEY(READERID) REFERENCES READER
)

